                      QUERY PLAN
------------------------------------------------------
 [                                                   +
   {                                                 +
     "Plan": {                                       +
       "Node Type": "Sort",                          +
       "Parallel Aware": false,                      +
       "Async Capable": false,                       +
       "Startup Cost": 76208.63,                     +
       "Total Cost": 77258.57,                       +
       "Plan Rows": 419978,                          +
       "Plan Width": 18,                             +
       "Actual Startup Time": 146.274,               +
       "Actual Total Time": 189.471,                 +
       "Actual Rows": 300000.00,                     +
       "Actual Loops": 1,                            +
       "Disabled": false,                            +
       "Sort Key": ["total DESC", "created_at DESC"],+
       "Sort Method": "external merge",              +
       "Sort Space Used": 10024,                     +
       "Sort Space Type": "Disk",                    +
       "Shared Hit Blocks": 15562,                   +
       "Shared Read Blocks": 0,                      +
       "Shared Dirtied Blocks": 0,                   +
       "Shared Written Blocks": 0,                   +
       "Local Hit Blocks": 0,                        +
       "Local Read Blocks": 0,                       +
       "Local Dirtied Blocks": 0,                    +
       "Local Written Blocks": 0,                    +
       "Temp Read Blocks": 2503,                     +
       "Temp Written Blocks": 2522,                  +
       "Plans": [                                    +
         {                                           +
           "Node Type": "Seq Scan",                  +
           "Parent Relationship": "Outer",           +
           "Parallel Aware": false,                  +
           "Async Capable": false,                   +
           "Relation Name": "orders",                +
           "Alias": "orders",                        +
           "Startup Cost": 0.00,                     +
           "Total Cost": 19755.78,                   +
           "Plan Rows": 419978,                      +
           "Plan Width": 18,                         +
           "Actual Startup Time": 4.255,             +
           "Actual Total Time": 45.256,              +
           "Actual Rows": 300000.00,                 +
           "Actual Loops": 1,                        +
           "Disabled": false,                        +
           "Shared Hit Blocks": 15556,               +
           "Shared Read Blocks": 0,                  +
           "Shared Dirtied Blocks": 0,               +
           "Shared Written Blocks": 0,               +
           "Local Hit Blocks": 0,                    +
           "Local Read Blocks": 0,                   +
           "Local Dirtied Blocks": 0,                +
           "Local Written Blocks": 0,                +
           "Temp Read Blocks": 0,                    +
           "Temp Written Blocks": 0                  +
         }                                           +
       ]                                             +
     },                                              +
     "Planning": {                                   +
       "Shared Hit Blocks": 94,                      +
       "Shared Read Blocks": 0,                      +
       "Shared Dirtied Blocks": 0,                   +
       "Shared Written Blocks": 0,                   +
       "Local Hit Blocks": 0,                        +
       "Local Read Blocks": 0,                       +
       "Local Dirtied Blocks": 0,                    +
       "Local Written Blocks": 0,                    +
       "Temp Read Blocks": 0,                        +
       "Temp Written Blocks": 0                      +
     },                                              +
     "Planning Time": 0.414,                         +
     "Triggers": [                                   +
     ],                                              +
     "Execution Time": 196.981                       +
   }                                                 +
 ]
(1 Zeile)
