"""Exact reviewed runtime translations; identifiers and serialized keys stay intact."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TRANSLATIONS = {
    "Session enthaelt {} Ereignisse, davon {} Fehlerhinweise.": "The session contains {} events, including {} error indicators.",
    "Doppelter Diagnosefall": "Duplicate diagnostic case",
    "Diagnose · {} · {} · {}": "Diagnosis · {} · {} · {}",
    "Zeile {}: unbekanntes Protokoll.": "Row {}: unknown protocol.",
    "Zu viele Herausgeber": "Too many publishers",
    "Maximal 128 Herausgeber": "At most 128 publishers are allowed",
    "Herausgebergrenze erreicht": "Publisher limit reached",
    "Unbekanntes Signaturschema": "Unknown signature schema",
    "Gleicher dokumentierter Endpunkt": "Same documented endpoint",
    "{} · {} · Ereignis {} (Rechnerzeit)": "{} · {} · event {} (host time)",
    "Fingerprint-Leser fehlgeschlagen": "Fingerprint reader failed",
    "Vault-Worker beendet.": "Vault worker ended.",
    "Prozess beendet: {exit}": "Process ended: {exit}",
    "Mehrere Fehler": "Multiple faults",
    "Simulation ohne Ergebnis": "Simulation returned no result",
    "Zeile {}: Metadaten zu lang oder mit Steuerzeichen.": "Row {}: metadata is too long or contains control characters.",
    "Evidence Mode starten und sichere Diagnosebeweise sammeln.": "Start Evidence Mode and collect safe diagnostic evidence.",
    "SSH-Befehl ist leer oder zu lang.": "The SSH command is empty or too long.",
    "Worker beendet ohne Ergebnis": "The worker ended without a result",
    "Dieser Auftragsstand ist bereits in der Bibliothek": "This job revision is already in the library",
    "Doppeltes Ticket oder zu viele Zustellungen": "Duplicate ticket or too many deliveries",
    "Ticket keinem Recovery-Fall zugeordnet": "The ticket is not assigned to a recovery case",
    "Zustellung bereits abgeschlossen": "Delivery already completed",
    "Jira-E-Mail und API-Token fehlen": "Jira email and API token are missing",
    "Nicht lesende oder anders gebundene Paketvoraussetzung": "The package prerequisite is not read-only or has a different binding",
    "Keine lokalen Fehler gefunden": "No local errors found",
    "Preflight hat keine blockierenden lokalen Probleme erkannt.": "Preflight found no blocking local issues.",
    "Keine Findings vorhanden.": "No findings are available.",
    "Verbindung starten und Timeline beobachten.": "Start the connection and monitor the timeline.",
    "Credential- oder NLA-Hinweise im Kontext erkannt.": "Credential or NLA indicators were found in the context.",
    "Zertifikatsrisiko im Kontext erkannt.": "A certificate risk was found in the context.",
    "Wiederholte Trennungen im Kontext erkannt.": "Repeated disconnections were found in the context.",
    "Langsamer Login oder schwarzer Bildschirm erkannt.": "A slow login or black screen was detected.",
    "DNS/TCP/RDP-Port Diagnose": "DNS/TCP/RDP port diagnosis",
    "Sicherer Netzwerk-Preflight ist der beste erste Schritt.": "A safe network preflight is the best first step.",
    "Keine eindeutige Root Cause gefunden.": "No clear root cause was found.",
    "Die Remote-Session wurde analysiert. Es wurden {} Ereignisse ausgewertet und sichere Diagnosebeweise gesammelt.": "The remote session was analyzed. {} events were reviewed and safe diagnostic evidence was collected.",
    "Timeline, KI-Beobachtungen und Policy-Entscheidungen pruefen.": "Review the timeline, AI observations, and policy decisions.",
    "Bei Bedarf mutierende Schritte separat freigeben.": "Approve state-changing steps separately if needed.",
    "Aktuelle Session: {} Events, vorherige Referenz: {} Events.": "Current session: {} events; previous reference: {} events.",
    "Unbekanntes Zertifikat: bei neuen Hosts normal, bei bestehenden Hosts pruefen.": "Unknown certificate: expected for new hosts; investigate for existing hosts.",
    "Zertifikat ist lokal vertraut.": "The certificate is locally trusted.",
    "Zertifikat wurde abgelehnt; Verbindung sollte blockiert bleiben.": "The certificate was rejected; the connection should remain blocked.",
    "Zertifikat hat sich geaendert; moeglicher Reinstall oder MITM-Risiko.": "The certificate changed; this may indicate a reinstall or a man-in-the-middle risk.",
    "Letzten erfolgreichen Fix pruefen: {}": "Review the last successful fix: {}",
    "Known Issue pruefen: {}": "Review the known issue: {}",
    "Host fehlt": "Host missing",
    "Das Profil hat keinen Hostnamen oder keine IP-Adresse.": "The profile has no hostname or IP address.",
    "Host im Profil eintragen.": "Enter a host in the profile.",
    "DNS aufgeloest": "DNS resolved",
    "{} wurde zu {} aufgeloest.": "{} resolved to {}.",
    "Keine Aktion erforderlich.": "No action is required.",
    "TCP-Port nicht erreichbar": "TCP port unreachable",
    "Der Zielhost antwortet nicht auf dem RDP-Port.": "The target host is not responding on the RDP port.",
    "Firewall, VPN, Routing und RDP-Port pruefen.": "Check the firewall, VPN, routing, and RDP port.",
    "Keine Adresse gefunden": "No address found",
    "DNS lieferte keine nutzbare Zieladresse.": "DNS returned no usable target address.",
    "Hostnamen oder DNS-Konfiguration pruefen.": "Check the hostname or DNS configuration.",
    "DNS-Fehler": "DNS error",
    "Hostnamen, DNS-Server oder Netzwerk pruefen.": "Check the hostname, DNS server, or network.",
    "Keine gespeicherten Credentials": "No saved credentials",
    "Das Profil hat weder Credential-Referenz noch ein temporaeres Passwort.": "The profile has neither a credential reference nor a temporary password.",
    "Credential speichern oder Passwort fuer die Session eingeben.": "Save credentials or enter a password for this session.",
    "Lösungsbibliothek voll oder Auftrag unvollständig": "The solution library is full or the job is incomplete",
    "Ungültige Voraussetzungen": "Invalid prerequisites",
    "OS {} passt nicht zu {}": "OS {} does not match {}",
    "Frische OS-Telemetrie fehlt": "Fresh OS telemetry is missing",
    "Dienst {service} vorhanden": "Service {service} is present",
    "Dienst {service} fehlt": "Service {service} is missing",
    "Vorhandensein von {service} ungeprüft": "The presence of {service} has not been checked",
    "Windows DPAPI erforderlich": "Windows DPAPI is required",
    "Lösungsbibliothek zu groß": "Solution library too large",
    "Ablauf oder Bildgröße ungültig": "Invalid workflow or image dimensions",
    "Erfolgskriterium und Wiederherstellung ergänzen": "Add success criteria and recovery instructions",
    "Sichtbare Nachbedingung benötigt ein nicht vertrauliches Zielwort und gültigen Kontext": "A visible postcondition requires a nonconfidential target word and valid context",
    "Ungültiger übertragbarer Anker": "Invalid transferable anchor",
    "Ungültiger semantischer Anker": "Invalid semantic anchor",
    "OCR veraltet: Zielbild erneut lesen": "OCR is stale: read the target image again",
    "OCR veraltet: aktuelles Bild erneut lesen und freigeben": "OCR is stale: read and approve the current image again",
    "Bildgröße geändert: Ablauf erneut prüfen / vormachen": "Image dimensions changed: review or demonstrate the workflow again",
    "Koordinate außerhalb des Bildes": "Coordinate outside the image",
    "Semantischer Schritt benötigt frische OCR desselben Bildes": "A semantic step requires fresh OCR from the same image",
    "Taste nicht freigegeben": "Key not authorized",
    "Parameterwert fehlt oder zu lang": "Parameter value missing or too long",
    "Ein neueres Bild derselben Zielsitzung ist erforderlich": "A newer image from the same target session is required",
    "Aktuelle OCR für Ergebnisnachweis fehlt": "Current OCR for outcome evidence is missing",
    "Ergebnis-OCR gehört nicht zum aktuellen Zielbild": "Outcome OCR does not belong to the current target image",
    "Realer Leseauftrag ist nicht an diesen Fall gebunden": "The real read request is not bound to this case",
    "Ziel fehlt": "Target missing",
    "Leseprüfung fehlgeschlagen, abgebrochen oder abgeschnitten": "The read check failed, was canceled, or was truncated",
    "Fremde oder veraltete Prüfantwort": "Unrelated or stale check response",
    "Prüfantwort außerhalb des Zeitfensters": "Check response outside the time window",
    "Modelllücke / Widerspruch": "Model gap / contradiction",
    "Szenario überschreitet das Prüflimit": "Scenario exceeds the check limit",
    "Ed25519-Schlüssel muss 32 Bytes haben": "An Ed25519 key must contain 32 bytes",
    "Datei zu groß": "File too large",
    "Schlüsselerzeugung fehlgeschlagen": "Key generation failed",
    "Schlüssel ungültig": "Invalid key",
    "Signierschlüssel besteht bereits oder kann nicht gespeichert werden": "The signing key already exists or cannot be saved",
    "Signierschlüssel nicht lesbar": "Cannot read the signing key",
    "Signiertes Paket zu groß": "Signed package too large",
    "Vertrauensspeicher beschädigt": "The trust store is corrupted",
    "Paket überschreitet 512 KiB": "Package exceeds 512 KiB",
    "Herausgeber nicht explizit vertraut oder widerrufen": "The publisher is not explicitly trusted or its trust was revoked",
    "Ungültige Herausgebersignatur": "Invalid publisher signature",
    "Ticketspeicher zu groß": "Ticket store too large",
    "Ticket-Ursprung nicht kanonisch": "The ticket origin is not canonical",
    "Ticket überschreitet Textgrenzen": "Ticket text exceeds the limits",
    "Störung überschreitet 4096 Bytes; Ticketbeschreibung kürzen": "Incident exceeds 4,096 bytes; shorten the ticket description",
    "Ungültige Zustellung": "Invalid delivery",
    "Ticketspeicher parallel geändert; neu laden": "The ticket store changed concurrently; reload it",
    "Bericht fehlt oder zu groß": "Report missing or too large",
    "Ticket fehlt": "Ticket missing",
    "Bericht bereits gesendet oder Zustellung ungeklärt; keine automatische Wiederholung": "The report was already sent or delivery is uncertain; no automatic retry",
    "Zustellung fehlt": "Delivery missing",
    "Aktive Zustellung erst nach mindestens zwei Minuten manuell klären": "Wait at least two minutes before manually reconciling an active delivery",
    "Ticket-JSON zu groß": "Ticket JSON too large",
    "Ticket-JSON ungültig": "Invalid ticket JSON",
    "Jira benötigt HTTPS-Ursprung ohne Pfad, Benutzer oder Query": "Jira requires an HTTPS origin without a path, username, or query",
    "Ticket-Schlüssel ungültig": "Invalid ticket key",
    "Jira-Antwort zu groß": "Jira response too large",
    "Jira-Antwort ungültig": "Invalid Jira response",
    "Jira nicht erreichbar": "Jira is unreachable",
    "Jira-Titel fehlt": "Jira title missing",
    "Jira-Revision fehlt": "Jira revision missing",
    "Zustellung unvollständig": "Delivery incomplete",
    "Jira-Zustellung ungeklärt; Ticket vor erneutem Versand manuell prüfen": "Jira delivery is uncertain; check the ticket manually before retrying",
    "Jira-Zustellung ungeklärt (HTTP {})": "Jira delivery is uncertain (HTTP {})",
    "Katalog unterstützt eine eindeutige Zielzuordnung je Paket": "The catalog supports one unambiguous target mapping per package",
    "Paket muss genau eine gebundene Dienstoperation enthalten; keine zusätzlichen Restore-Schritte": "The package must contain exactly one bound service operation and no additional restore steps",
    "Paketoperation passt nicht zur geprobten Dienständerung": "The package operation does not match the rehearsed service change",
    "HTTP-Nachweis erforderlich": "HTTP evidence is required",
    "Katalogbeleg benötigt öffentliche GET-Prüfungen": "Catalog evidence requires public GET checks",
    "Paketprüfungen passen nicht zu Klonbelegen": "Package checks do not match clone evidence",
    "Paket-HTTP-Test weicht vom tatsächlichen Beleg ab": "The package HTTP check differs from the actual evidence",
    "Wiederherstellungsplan nicht aktuell": "The recovery plan is not current",
    "Katalog zu groß": "Catalog too large",
    "Maximal 64 Katalogeinträge": "At most 64 catalog entries are allowed",
    "Ungültiger Katalogeintrag": "Invalid catalog entry",
    "Katalog parallel geändert; neu laden": "The catalog changed concurrently; reload it",
    "Ein Ziel je Katalogpaket erforderlich": "One target is required per catalog package",
    "HTTP erforderlich": "HTTP is required",
    "Nur öffentliche GETs im Katalog": "Only public GET requests are allowed in the catalog",
    "Zuvor beobachtete Abhängigkeit; Zuordnung erneut prüfen": "Previously observed dependency; review the mapping again",
    " (unvollständig)": " (incomplete)",
    "Ungültiger Host oder Port (DNS-Name oder IP erforderlich).": "Invalid host or port (a DNS name or IP address is required).",
    "SSH-Benutzer darf nur Buchstaben, Zahlen, Punkt, _ und - enthalten.": "SSH usernames may contain only letters, digits, periods, underscores, and hyphens.",
    "Dateipfad ist leer oder enthält Steuerzeichen/SFTP-Muster.": "The file path is empty or contains control characters or SFTP patterns.",
    "Lokaler Dateipfad muss absolut sein.": "The local file path must be absolute.",
    "Ungültiger Dienstname.": "Invalid service name.",
    "Quelle: {}\\n{} {:?}\\n{}": "Source: {}\\n{} {:?}\\n{}",
    "Auftragsliste voll; abgeschlossene Aufträge entfernen.": "The job list is full; remove completed jobs.",
    "Inventar überschreitet 2 MiB.": "Inventory exceeds 2 MiB.",
    "CSV ungültig; Spalten name,host erforderlich.": "Invalid CSV; name and host columns are required.",
    "JSON ungültig; Array mit name und host erforderlich.": "Invalid JSON; an array containing name and host is required.",
    "Maximal 2000 Inventareinträge pro Import.": "At most 2,000 inventory entries are allowed per import.",
    "Zeile {}: ungültiger Host/Port.": "Row {}: invalid host or port.",
    "Zeile {}: Name fehlt.": "Row {}: name is missing.",
    "Active Directory / aktuelle Windows-Identität": "Active Directory / current Windows identity",
    "Entra ID / explizites Graph-Zugriffstoken; Anzeigenamen sind unbestätigte Zielkandidaten": "Entra ID / explicitly supplied Graph access token; display names are unverified host candidates",
    "Bitwarden-Eintrag benötigt eine gültige UUID.": "A Bitwarden item requires a valid UUID.",
    "Vault-Antwort ist ungültig.": "Invalid vault response.",
    "Vault-Eintrag ist kein Login.": "The vault item is not a login.",
    "Vault-Login hat keinen Benutzernamen.": "The vault login has no username.",
    "Vault-Login hat kein Passwort.": "The vault login has no password.",
    "Diese Vault-Integration benötigt Windows und DPAPI.": "This vault integration requires Windows and DPAPI.",
    "BW_SESSION fehlt. Bitwarden extern entsperren und Relayne mit geerbter Sitzung starten.": "BW_SESSION is missing. Unlock Bitwarden externally and start Relayne with the inherited session.",
    "bw.exe konnte nicht gestartet werden. Offizielle Bitwarden CLI im PATH erforderlich.": "Could not start bw.exe. The official Bitwarden CLI must be on PATH.",
    "Vault-Ausgabekanal fehlt.": "The vault output channel is missing.",
    "Vault-Abruf abgebrochen, Zeitlimit oder Größenlimit erreicht.": "Vault retrieval was canceled or reached its time or size limit.",
    "Vault-Ausgabe nicht verfügbar.": "Vault output is unavailable.",
    "Vault-Ausgabe unvollständig.": "Vault output is incomplete.",
    "Vault-Abruf fehlgeschlagen. Sitzung, Eintrag-ID und Berechtigung extern prüfen.": "Vault retrieval failed. Check the session, item ID, and permissions externally.",
    "Vault-Prozessstatus nicht verfügbar.": "Vault process status is unavailable.",
}
for name in ("operations.rs", "integrations.rs", "package_trust.rs", "recovery_tickets.rs", "repair_catalog.rs", "incident.rs", "recommendations.rs", "teaching.rs", "diagnostic_lab.rs", "diagnostic_lab/adapter.rs", "diagnostic_lab/comparison.rs", "ai.rs", "certificate.rs", "memory.rs", "diagnostics.rs", "equivalence.rs"):
    path = ROOT / "src" / name
    source = path.read_text(encoding="utf-8")
    for old, new in TRANSLATIONS.items():
        source = source.replace('"' + old + '"', '"' + new + '"')
    path.write_text(source, encoding="utf-8", newline="")
